model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

#[mcp_servers.jetbrains]
#url = "http://127.0.0.1:64344/stream"

[features]
shell_snapshot = true
unified_exec = true
multi_agent = true
suppress_unstable_features_warning = true
